version: "2.3"
services:
  rust-server:
    volumes:
      - type: bind
        source: ./rust/
        target: /opt/rustserver/server/rust
      - type: bind
        source: ./rust/server.log
        target: /opt/rustserver/server.log
    # cpuset: 0-1
    mem_reservation: 3000m
    build:
      context: .
    env_file:
      - vars.env
    ports:
    - "28015:28015/udp"
    - "28016:28016"
